### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by struckchure** [Horlakz/goals-app#1]
```js
// authService.js
...
const authService = [
    register,
]
...
```

then you referenced `authService.register`, if that's how you want it, do this instead;

```js
// authService.js
...
const authService = {
    register,
}
...
```

**Comment by horlakz** [comment]
ahhr, see me thinking solution is here
ok nau

**Comment by struckchure** [comment]
what'd you expect to find??

:neutral_face:

**Comment by horlakz** [comment]
ohh i just understood you now, I used the wrong brackets
i was sha wondering, thanks man
fixed
